### ISSUE TITLE
Error removing user from team

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#157] opened 2017-11-10 08:22 UTC
When a custodian tries to remove a user from a team an error is thrown.

`No route matches [DELETE] "/team_members/6"`

**URL**
/team_members/6

**Steps to reproduce**
1. Log in as a custodian
2. Click 'Manage Team'
3. Click in 'Change' for one of the users in the team
4. Click remove

**Expected result**
To remove the user from the team

**Actual result**
An error is thrown: `http://localhost:3000/team_members/6`

/cc @Maidment64

**Comment by gidsg** [comment] 2017-11-15 12:08
Cannot reproduce so closing. Please re-open if you can reliably reproduce.

**Closed by gidsg** 2017-11-15 12:08 UTC
Labels: Bug
