### ISSUE TITLE
Start date and end date fields are not validated against datetime

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#79] opened 2017-10-17 17:30 UTC
When adding a new register record the start date and end date fields are no validated if the input is not a valid date

**URL:**

https://managing-registers-staging.cloudapps.digital/country

**Steps to recreate:**

1. Login as any user permission
2. Click on the 'Country' register link
3. Add details to the new record including invalid datetime e.g. "01011abc"
4. Click 'Continue'

**Expected result:**

The data in the input is invalid and the user receives a validation message

**Actual result:**

![screen shot 2017-10-17 at 18 30 27](https://user-images.githubusercontent.com/27765242/31679525-4b6f47d4-b369-11e7-91c3-a4afeff06823.png)

**Comment by gidsg** [comment] 2017-10-18 10:38
I am unable to reproduce this, this works for me following your steps:
<img width="564" alt="screen shot 2017-10-18 at 11 37 37" src="https://user-images.githubusercontent.com/1764158/31714585-c56c3a76-b3f8-11e7-8a67-f9546aed1385.png">
I am going to close this, but will re-open if you can demo reproducing this to me!

**Comment by gidsg** [comment] 2017-10-18 13:55
OK, I have reproduced this now if for example the date input `123X` is being accepted.

**Closed** 2017-10-19 14:56 UTC
Labels: Backend, Bug
